(env) C:\WORKS_2\WS\WS_Others.prog\prog\D-7\2_2\VIRTUAL\Admin_Projects>python ma
nage.py runserver
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper
 at 0x0000000003EBAE18>
Traceback (most recent call last):
  File "C:\WORKS_2\WS\WS_Others\prog\D-7\2_2\VIRTUAL\env\lib\site-packages\djang
o\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\WORKS_2\WS\WS_Others\prog\D-7\2_2\VIRTUAL\env\lib\site-packages\djang
o\core\management\commands\runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "C:\WORKS_2\WS\WS_Others\prog\D-7\2_2\VIRTUAL\env\lib\site-packages\djang
o\core\management\base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\WORKS_2\WS\WS_Others\prog\D-7\2_2\VIRTUAL\env\lib\site-packages\djang
o\core\management\base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\WORKS_2\WS\WS_Others\prog\D-7\2_2\VIRTUAL\env\lib\site-packages\djang
o\core\checks\registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\WORKS_2\WS\WS_Others\prog\D-7\2_2\VIRTUAL\env\lib\site-packages\djang
o\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "C:\WORKS_2\WS\WS_Others\prog\D-7\2_2\VIRTUAL\env\lib\site-packages\djang
o\core\checks\urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "C:\WORKS_2\WS\WS_Others\prog\D-7\2_2\VIRTUAL\env\lib\site-packages\djang
o\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\WORKS_2\WS\WS_Others\prog\D-7\2_2\VIRTUAL\env\lib\site-packages\djang
o\urls\resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\WORKS_2\WS\WS_Others\prog\D-7\2_2\VIRTUAL\env\lib\site-packages\djang
o\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\WORKS_2\WS\WS_Others\prog\D-7\2_2\VIRTUAL\env\lib\site-packages\djang
o\urls\resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\WORKS_2\WS\WS_Others\prog\D-7\2_2\VIRTUAL\env\lib\importlib\__init__.
py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\WORKS_2\WS\WS_Others.prog\prog\D-7\2_2\VIRTUAL\Admin_Projects\Admin_P
rojects\urls.py", line 19, in <module>
    from mm import views
  File "C:\WORKS_2\WS\WS_Others.prog\prog\D-7\2_2\VIRTUAL\Admin_Projects\mm\view
s.py", line 25, in <module>
    from pip._vendor.requests.api import request
  File "C:\WORKS_2\WS\WS_Others\prog\D-7\2_2\VIRTUAL\env\lib\site-packages\pip\_
vendor\requests\__init__.py", line 94, in <module>
    from pip._internal.utils.compat import WINDOWS
  File "C:\WORKS_2\WS\WS_Others\prog\D-7\2_2\VIRTUAL\env\lib\site-packages\pip\_
internal\__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\WORKS_2\WS\WS_Others\prog\D-7\2_2\VIRTUAL\env\lib\site-packages\pip\_
internal\cli\autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\WORKS_2\WS\WS_Others\prog\D-7\2_2\VIRTUAL\env\lib\site-packages\pip\_
internal\cli\main_parser.py", line 12, in <module>
    from pip._internal.commands import (
  File "C:\WORKS_2\WS\WS_Others\prog\D-7\2_2\VIRTUAL\env\lib\site-packages\pip\_
internal\commands\__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "C:\WORKS_2\WS\WS_Others\prog\D-7\2_2\VIRTUAL\env\lib\site-packages\pip\_
internal\commands\completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "C:\WORKS_2\WS\WS_Others\prog\D-7\2_2\VIRTUAL\env\lib\site-packages\pip\_
internal\cli\base_command.py", line 18, in <module>
    from pip._internal.download import PipSession
  File "C:\WORKS_2\WS\WS_Others\prog\D-7\2_2\VIRTUAL\env\lib\site-packages\pip\_
internal\download.py", line 325, in <module>
    class PipSession(requests.Session):
AttributeError: module 'pip._vendor.requests' has no attribute 'Session'
バッチ ジョブを終了しますか (Y/N)? n